<?php

/**
 * Registering migrate classes.
 */
function easyddb_migration_flush_caches() {
  $common_arguments = array(
    'source_connection' => 'migration',
    'source_version' => 7,
  );

  // User migration group.
  $arguments = $common_arguments + array(
    'description' => t('Migration of roles from easyting'),
    'machine_name' => 'roleMigration',
    'role_mappings' => array(
      "administrator" => "administrators",
      "local administrator" => "local administrator",
      "editor" => "editor",
      "journalist" => "guest blogger",
    ),
  );
  Migration::registerMigration('EasyDDBRoleMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of users from easyting'),
    'machine_name' => 'userMigration',
    'role_migration' => 'roleMigration',
  );
  Migration::registerMigration('EasyDDBUserMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of users token from easyting'),
    'machine_name' => 'userTokenMigration',
  );
  Migration::registerMigration('EasyDDBUserTokenMigration', $arguments['machine_name'], $arguments);

  // Taxonomy migration group.
  $arguments = $common_arguments + array(
    'description'            => t('Migration of taxonomy Category'),
    'machine_name'           => 'categoryMigration',
    'source_vocabulary'      => 'category',
    'destination_vocabulary' => 'category',
    'vocabulary_name'        => t('Category'),
    'vocabulary_description' => t('Categories vocabulary.'),
  );
  Migration::registerMigration('EasyDDBTaxonomyMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description'            => t('Migration of taxonomy Tags'),
    'machine_name'           => 'tagsMigration',
    'source_vocabulary'      => 'ding_content_tags',
    'destination_vocabulary' => 'ding_content_tags',
    'vacabulary_name'        => t('Tags'),
    'vacabulary_description' => t('Tags vocabulary.'),
  );
  Migration::registerMigration('EasyDDBTaxonomyMigration', $arguments['machine_name'], $arguments);

  $section = $common_arguments + array(
    'description'            => t('Migration of taxonomy Section'),
    'machine_name'           => 'sectionMigration',
    'source_vocabulary'      => 'eddb_editorial_base',
    'destination_vocabulary' => 'editorial_base',
    'vocabulary_name'        => t('Section'),
    'vocabulary_description' => t('Vocabulary for Editorial Base functionality.'),
  );
  Migration::registerMigration('EasyDDBTaxonomyMigration', $section['machine_name'], $section);

  $dams_category = $common_arguments + array(
    'description'            => t('Migration of taxonomy Mediebibliotekskategorier'),
    'machine_name'           => 'damsCategoryMigration',
    'source_vocabulary'      => 'dams_category',
    'destination_vocabulary' => 'dams_category',
    'vocabulary_name'        => t('Mediebibliotekskategorier'),
    'vocabulary_description' => t('Vocabulary for dams module.'),
  );
  Migration::registerMigration('EasyDDBTaxonomyMigration', $dams_category['machine_name'], $dams_category);
}

/**
 * Implements hook_migrate_api().
 */
function easyddb_migration_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}
