<?php

/**
 * Registering migrate classes.
 */
function easyddb_migration_flush_caches() {
  $common_arguments = array(
    'source_connection' => 'migration',
    'source_version' => 7,
  );

  // User migration group.
  $arguments = $common_arguments + array(
    'description' => t('Migration of roles from easyting'),
    'machine_name' => 'roleMigration',
    'role_mappings' => array(
      "administrator" => "administrators",
      "local administrator" => "local administrator",
      "editor" => "editor",
      "journalist" => "guest blogger",
    ),
  );
  Migration::registerMigration('EasyDDBRoleMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of users from easyting'),
    'machine_name' => 'userMigration',
    'role_migration' => 'roleMigration',
  );
  Migration::registerMigration('EasyDDBUserMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of users token from easyting'),
    'machine_name' => 'userTokenMigration',
  );
  Migration::registerMigration('EasyDDBUserTokenMigration', $arguments['machine_name'], $arguments);

  // Taxonomy migration group.
  $arguments = $common_arguments + array(
    'description' => t('Migration of taxonomy Category'),
    'machine_name' => 'categoryMigration',
    'source_vocabulary' => 'category',
    'destination_vocabulary' => 'category',
  );
  Migration::registerMigration('EasyDDBCategoryMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of taxonomy Tags'),
    'machine_name' => 'tagsMigration',
    'source_vocabulary' => 'ding_content_tags',
    'destination_vocabulary' => 'ding_content_tags',
  );
  Migration::registerMigration('EasyDDBTagsMigration', $arguments['machine_name'], $arguments);

  // Common migrations.
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from easyting'),
    'machine_name' => 'fileMigration',
    'destination_dir' => 'public://',
    'source_dir' => 'public://migration/source',
    'user_migration' => 'userMigration',
  );
  Migration::registerMigration('EasyDDBFileMigration', $arguments['machine_name'], $arguments);

  // Nodes migration group.
  $arguments = $common_arguments + array(
    'description' => t('Migration of content type News'),
    'machine_name' => 'newsMigration',
    'source_type' => 'ding_news',
    'destination_type' => 'ding_news',
    'user_migration' => 'userMigration',
  );
  Migration::registerMigration('EasyDDBNewsMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of content type Events'),
    'machine_name' => 'eventsMigration',
    'source_type' => 'ding_event',
    'destination_type' => 'ding_event',
    'user_migration' => 'userMigration',
  );
  Migration::registerMigration('EasyDDBEventsMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of content type Library'),
    'machine_name' => 'libraryMigration',
    'source_type' => 'ding_library',
    'destination_type' => 'ding_library',
    'user_migration' => 'userMigration',
  );
  Migration::registerMigration('EasyDDBLibraryMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of content type Page'),
    'machine_name' => 'pageMigration',
    'source_type' => 'ding_page',
    'destination_type' => 'ding_page',
    'user_migration' => 'userMigration',
  );
  Migration::registerMigration('EasyDDBPageMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of content type Campaign'),
    'machine_name' => 'campaignMigration',
    'source_type' => 'ding_campaign',
    'destination_type' => 'ding_campaign',
    'user_migration' => 'userMigration',
  );
  Migration::registerMigration('EasyDDBCampaignMigration', $arguments['machine_name'], $arguments);

  // OG migration group.
  $arguments = $common_arguments + array(
    'description' => t('Migration of og membership type'),
    'machine_name' => 'ogMembershipTypeMigration',
  );
  Migration::registerMigration('EasyDDBOgMembershipTypeMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of og membership'),
    'machine_name' => 'ogMembershipMigration',
  );
  Migration::registerMigration('EasyDDBOgMembershipMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of og menu'),
    'machine_name' => 'ogMenuMigration',
  );
  Migration::registerMigration('EasyDDBOgMenuMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of og role'),
    'machine_name' => 'ogRoleMigration',
  );
  Migration::registerMigration('EasyDDBOgRoleMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of og role permission'),
    'machine_name' => 'ogRolePermissionMigration',
  );
  Migration::registerMigration('EasyDDBOgRolePermissionMigration', $arguments['machine_name'], $arguments);

  $arguments = $common_arguments + array(
    'description' => t('Migration of og users roles'),
    'machine_name' => 'ogUsersRolesMigration',
  );
  Migration::registerMigration('EasyDDBOgUsersRolesMigration', $arguments['machine_name'], $arguments);
}

/**
 * Implements hook_migrate_api().
 */
function easyddb_migration_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}
